/**
 * SiemensHypixelApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ItemDto { 
    material?: string | null;
    color?: string | null;
    name?: string | null;
    category?: string | null;
    tier?: string | null;
    stats?: any | null;
    npc_sell_price?: number | null;
    id?: string | null;
}

